# Generated by Django 6.0.2 on 2026-02-15 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_deleted_at_contract_deleted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criado"),
                            ("UPDATE", "Atualizado"),
                            ("DELETE", "Deletado (soft delete)"),
                            ("APPROVE", "Aprovado"),
                            ("REJECT", "Rejeitado"),
                            ("PAID", "Marcado como Pago"),
                            ("FAILED", "Marcado como Falhou"),
                            ("RESTORE", "Restaurado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "object_display",
                    models.CharField(blank=True, max_length=255),
                ),
                ("changes", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="contracts_a_model_n_83779e_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="contracts_a_user_id_cf8c3a_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="contracts_a_action_5ad5c5_idx",
                    ),
                ],
            },
        ),
    ]
