# Generated by Django 6.0.2 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_auditlog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["status"], name="contracts_c_status_6e6d2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["manager"], name="contracts_c_manager_442326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["created_at"], name="contracts_c_created_24b8d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["is_deleted"], name="contracts_c_is_dele_5a6f80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["contract"], name="contracts_m_contract_9e1f9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["status"], name="contracts_m_status_92f6f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["created_at"], name="contracts_m_created_5b4f1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["approved_at"], name="contracts_m_approved_2a4e8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["contract"], name="contracts_p_contract_5b1b49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status"], name="contracts_p_status_2c9e9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["paid_at"], name="contracts_p_paid_at_3a7e63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="contracts_p_created_5e1f4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["contract"], name="contracts_a_contract_3f7c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["created_at"], name="contracts_a_created_15f8d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractstatushistory",
            index=models.Index(
                fields=["contract"], name="contracts_csh_contract_6e4b2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractstatushistory",
            index=models.Index(
                fields=["changed_at"], name="contracts_csh_changed_0f2b1c_idx"
            ),
        ),
    ]
