# Generated by Django 6.0.2 on 2026-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='contracts_a_contrac_638766_idx',
            old_name='contracts_a_contract_3f7c0f_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='contracts_a_created_a6a0b1_idx',
            old_name='contracts_a_created_15f8d2_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_status_aa7a80_idx',
            old_name='contracts_c_status_6e6d2d_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_manager_fa6169_idx',
            old_name='contracts_c_manager_442326_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_created_526229_idx',
            old_name='contracts_c_created_24b8d7_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_is_dele_58ba08_idx',
            old_name='contracts_c_is_dele_5a6f80_idx',
        ),
        migrations.RenameIndex(
            model_name='contractstatushistory',
            new_name='contracts_c_contrac_7d5bff_idx',
            old_name='contracts_csh_contract_6e4b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='contractstatushistory',
            new_name='contracts_c_changed_a3bf4a_idx',
            old_name='contracts_csh_changed_0f2b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='contracts_m_contrac_60b4bb_idx',
            old_name='contracts_m_contract_9e1f9d_idx',
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='contracts_m_status_a731d8_idx',
            old_name='contracts_m_status_92f6f0_idx',
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='contracts_m_created_44bbd2_idx',
            old_name='contracts_m_created_5b4f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='measurement',
            new_name='contracts_m_approve_5c8bcd_idx',
            old_name='contracts_m_approved_2a4e8b_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='contracts_p_contrac_145f99_idx',
            old_name='contracts_p_contract_5b1b49_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='contracts_p_status_3bb14a_idx',
            old_name='contracts_p_status_2c9e9d_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='contracts_p_paid_at_1b8793_idx',
            old_name='contracts_p_paid_at_3a7e63_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='contracts_p_created_a62cb3_idx',
            old_name='contracts_p_created_5e1f4c_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('CREATE', 'Criado'),
                    ('UPDATE', 'Atualizado'),
                    ('DELETE', 'Deletado (soft delete)'),
                    ('APPROVE', 'Aprovado'),
                    ('REJECT', 'Rejeitado'),
                    ('REOPEN', 'Reaberto (Rejeição Revertida)'),
                    ('PAID', 'Marcado como Pago'),
                    ('FAILED', 'Marcado como Falhou'),
                    ('RESTORE', 'Restaurado'),
                ],
                max_length=20,
            ),
        ),
    ]
