# Generated by Django 6.0.2 on 2026-03-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_rename_contracts_a_contract_3f7c0f_idx_contracts_a_contrac_638766_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cnpj_empresa_contratada',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='contract',
            name='empresa_contratada',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='empresa_contratante',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
