# Generated by Django 6.0.2 on 2026-03-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_cnpj_empresa_contratada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cnpj_empresa_contratante',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
