# Generated by Django 6.0.2 on 2026-03-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_cnpj_empresa_contratante'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
