# Generated by Django 6.0.2 on 2026-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_measurement_approved_by_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='anexo_nota_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='data_emissao_nota',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='valor_nota_fiscal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
