# Generated by Django 6.0.2 on 2026-03-25 01:09

from django.db import migrations


GROUPS = ["ADMIN", "GESTOR", "FINANCEIRO", "FORNECEDOR", "SUPER"]


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in GROUPS:
        Group.objects.get_or_create(name=name)


def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=GROUPS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_payment_nf_fields"),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
